---
title: "'In a Perishing Condition': The Fate of Black Inmates in the Philadelphia Almshouse, 1796-1803"
author: "Jessica Foster"
date: "2023-05-04"
output: html_document
---

```{r Data Preprocessing, include=FALSE}
# Load libraries
library(DigitalMethodsData)
library(tidyverse)
library(pdftools)
library(qpdf)
library(docxtractr)
library(ggplot2)

# Load the almshouse_admissions dataset from the DigitalMethodsData library
data("almshouse_admissions")

# Save the almshouse_admissions dataset as a csv file in this repository
write.csv(almshouse_admissions, file = "almshouse_admissions.csv", row.names = TRUE, col.names = TRUE)

# almshouse_admissions uses numeric codes for the Descriptions.by.Clerk and Reason.Discharged columns. I downloaded the codebook for this dataset from Billy G. Smith's original repository: https://repository.upenn.edu/mead/42/. To make the codebook easier to work with in R, I converted the code lists to tables in Word before uploading it to this repository. Now we can scrape the content from the Word doc using the `docxtractr` package: https://github.com/hrbrmstr/docxtractr

# Read in the Almshouse Admissions Codebook Word doc
almshouse.codebook <- read_docx("Codebook Almshouse Admissions 1796-1803 - with tables.docx")

# Count the number of tables in the Word doc
docx_tbl_count(almshouse.codebook)

# Describe each table
docx_describe_tbls(almshouse.codebook)

# Extract the table of "Description" codes and save to variable
description.codes <- docx_extract_tbl(almshouse.codebook, 1, header=TRUE)

# Extract the table of "Reason for Discharge" codes and save to variable
reason.for.discharge.codes <- docx_extract_tbl(almshouse.codebook, 2, header=TRUE)

# Remove the leading zeros from numbers in description.codes so they match the format of the numbers in the Descriptions.by.Clerk column in almshouse_admissions
description.codes <- description.codes %>%
  mutate(Code = as.numeric(Code))

# Remove the leading zeros from numbers in reason.for.discharge.codes so they match the format of the numbers in the Reason.Discharged column in almshouse_admissions
reason.for.discharge.codes <- reason.for.discharge.codes %>%
  mutate(Code = as.numeric(Code))

# Join description.codes dataframe to almshouse_admissions dataframe
almshouse_admissions <- left_join(almshouse_admissions, description.codes, by=c("Descriptions.by.Clerk"="Code"))

# Join reason.for.discharge.codes dataframe to almshouse_admissions dataframe
almshouse_admissions <- left_join(almshouse_admissions, reason.for.discharge.codes, by=c("Reason.Discharged"="Code"))
```

On December 2, 1800, the Philadelphia Almshouse admitted Sarah Bordley and her five-year-old daughter Ann. Born into slavery in Cecil County, Maryland, Sarah had been manumitted upon the death of her master, Robert Thompson. Like thousands of other newly freed slaves, Sarah migrated north to Philadelphia, which had become known as "a center of abolitionism and benevolence toward free blacks."[^1] Life in a northern city, however, brought a new set of difficulties, especially for formerly enslaved individuals lacking urban skills, formal education, and stable health. According to her own account, recorded by the almshouse clerk, Sarah worked in Philadelphia for two years as "a Washerwoman" to support herself and Ann, until "pains through all her limbs" made it impossible for her to earn a living. By the time Sarah and her daughter sought shelter in the almshouse, they both "were in a perishing condition."[^2]


[^1]: Gary B. Nash, <em>Forging Freedom: The Formation of Philadelphia's Black Community, 1720-1840</em> (Cambridge, MA: Harvard University Press, 1988), 137, Ebook, https://hdl-handle-net.libproxy.clemson.edu/2027/heb01388.0001.001.
[^2]: Billy G. Smith and Cynthia Shelton, "THE DAILY OCCURRENCE DOCKET OF THE PHILADELPHIA ALMSHOUSE: SELECTED
ENTRIES, 1800–1804," <em>Pennsylvania History: A Journal of Mid-Atlantic Studies</em> 52, no. 3 (July 1985): 192, https://www.jstor.org/stable/27773054. See also Billy G. Smith, <em>The "Lower Sort": Philadelphia’s Laboring People, 1750-1800</em> (Ithaca, NY: Cornell University Press, 1990), 196.

---
### Bibliography

Nash, Gary B. <em>Forging Freedom: The Formation of Philadelphia's Black Community, 1720-1840</em>. Cambridge, MA: Harvard University Press, 1988. Ebook. https://hdl-handle-net.libproxy.clemson.edu/2027/heb01388.0001.001.

Smith, Billy G. <em>The "Lower Sort": Philadelphia’s Laboring People, 1750-1800</em>. Ithaca, NY: Cornell University Press, 1990.

Smith, Billy G., and Cynthia Shelton. "THE DAILY OCCURRENCE DOCKET OF THE PHILADELPHIA ALMSHOUSE: SELECTED
ENTRIES, 1800–1804." <em>Pennsylvania History: A Journal of Mid-Atlantic Studies</em> 52, no. 3 (July 1985): 183-205. https://www.jstor.org/stable/27773054.
